# Generated by Django 2.2.3 on 2019-07-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db2', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
